--Eu quero fazer um relatório para poder ver, dentro de um determinado mês, 
--quais foram os clientes que ultrapassaram ou não esse volume de compra. 

SELECT 
C.CPF, C.NOME,C.[VOLUME DE COMPRA], VENDA.MES_ANO, VENDA.TOTAL_VOLUME,
(CASE 
	WHEN C.[VOLUME DE COMPRA] >= VENDA.TOTAL_VOLUME THEN 'VENDAS VALIDAS'
	ELSE 'VENDAS INVALIDAS' END) AS VALIDACAO
FROM CLIENTES C
JOIN(
	SELECT NF.CPF, 
	CONVERT(VARCHAR(7), NF.DATA, 120) AS MES_ANO,  --convertendo coluna NF.DATA para VARCHAR com um tamanho de 7 caracteres. o estilo 120,  representa  "YYYY-MM".
	SUM(INF.QUANTIDADE) TOTAL_VOLUME
	FROM NF
	JOIN ITEM_NF INF ON INF.NUMERO = NF.NUMERO
	GROUP BY 
	NF.CPF, 
	CONVERT(VARCHAR(7), NF.DATA, 120)) VENDA  ON VENDA.CPF=C.CPF
WHERE VENDA.MES_ANO='2015-01'


---

SELECT 
C.CPF, C.NOME,C.[VOLUME DE COMPRA], VENDA.MES_ANO, VENDA.TOTAL_VOLUME,
(CASE 
	WHEN C.[VOLUME DE COMPRA] >= VENDA.TOTAL_VOLUME THEN 'VENDAS VALIDAS'
	ELSE 'VENDAS INVALIDAS' END) AS VALIDACAO,
ROUND((1 - ([VOLUME DE COMPRA]/VENDA.TOTAL_VOLUME)) * 100,2) AS DIFERENCA
FROM CLIENTES C

JOIN(
	SELECT NF.CPF, 
	CONVERT(VARCHAR(7), NF.DATA, 120) AS MES_ANO,  --convertendo coluna NF.DATA para VARCHAR com um tamanho de 7 caracteres. o estilo 120,  representa  "YYYY-MM".
	SUM(INF.QUANTIDADE) TOTAL_VOLUME
	FROM NF
	JOIN ITEM_NF INF ON INF.NUMERO = NF.NUMERO
	GROUP BY 
	NF.CPF, 
	CONVERT(VARCHAR(7), NF.DATA, 120)) VENDA  ON VENDA.CPF=C.CPF
WHERE C.[VOLUME DE COMPRA] < VENDA.TOTAL_VOLUME