SELECT 
[NOME DO PRODUTO]
,[PREÇO DE LISTA]
,CASE
	WHEN [PREÇO DE LISTA] >= 12 THEN 'CARO'
	WHEN [PREÇO DE LISTA] BETWEEN 7 AND 12 THEN 'NA MÉDIA'
	ELSE 'BARATO'
END AS CLASSIFICACAO_PRECO
FROM PRODUTOS
WHERE 
SABOR='Manga'

--SE QUISER AGRUPAR O CASE TEM QUE REPETIR NO GROUP
SELECT 
CASE
	WHEN [PREÇO DE LISTA] >= 12 THEN 'CARO'
	WHEN [PREÇO DE LISTA] BETWEEN 7 AND 12 THEN 'NA MÉDIA'
	ELSE 'BARATO'
END AS CLASSIFICACAO_PRECO
,COUNT(*) AS [NUMERO DE PRODUTOS]
FROM PRODUTOS
GROUP BY
CASE
	WHEN [PREÇO DE LISTA] >= 12 THEN 'CARO'
	WHEN [PREÇO DE LISTA] BETWEEN 7 AND 12 THEN 'NA MÉDIA'
	ELSE 'BARATO'
END


--EXERCICIO

SELECT 
NOME, [LIMITE DE CREDITO]
,CASE
	WHEN [LIMITE DE CREDITO] >= 150000 THEN 'GRANDE'
	WHEN [LIMITE DE CREDITO] <= 150000 AND [LIMITE DE CREDITO] >=110000 THEN 'MÉDIOS'
	WHEN [LIMITE DE CREDITO] < 110000 THEN 'PEQUENOS'
END [TIPO CLIENTE]
FROM CLIENTES