SELECT * FROM [TABELA DE PRODUTOS]

SELECT [NOME DO PRODUTO],
CASE 
	WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
	WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
END
FROM [TABELA DE PRODUTOS]


SELECT [NOME DO PRODUTO],
CASE 
	WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
	WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
END CLASSIFICACAO,
AVG([PREÇO DE LISTA]) MEDIA_PRECO
FROM
[TABELA DE PRODUTOS]

GROUP BY [NOME DO PRODUTO],

CASE WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
	WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO' 
END 

SELECT YEAR(DATA), COUNT(*) FROM [NOTAS FISCAIS] GROUP BY YEAR(DATA)


--Veja o ano de nascimento dos clientes e classifique-os como: nascidos antes de 1990 são adultos, nascidos entre 1990 e 1995 são 
--jovens e nascidos depois de 1995 são crianças. Liste o nome do cliente e esta classificação.
SELECT 
CPF,
NOME,
[DATA DE NASCIMENTO],
CASE 
	WHEN YEAR([DATA DE NASCIMENTO]) < 1990 THEN 'ADULTOS'
	WHEN YEAR([DATA DE NASCIMENTO]) BETWEEN 1990 AND 1995 THEN 'JOVENS'
	WHEN YEAR([DATA DE NASCIMENTO]) > 1995 THEN 'CRIANCAS'
END CLASSIFICACAO
FROM [TABELA DE CLIENTES]

	

