-- FAZENDO UM PRA RETORNAR FATURAMENTO
--PRIMEIRO FIZ O SELECT
SELECT SUM(QUANTIDADE*PREÇO) AS FATURAMENTEO FROM ITEM_NF INF
JOIN NF ON INF.NUMERO = NF.NUMERO
JOIN CLIENTES C ON NF.CPF = C.CPF
WHERE C.BAIRRO =	'Tijuca'

-- EM SEGUIDA COLOQUEI NO CREATE FUNCTION
DROP FUNCTION FaturamentoTotal
CREATE FUNCTION FaturamentoTotal (@bairro VARCHAR(50)) -- NOME E PARAMETRO QUE VAI INFORMAR
RETURNS VARCHAR
AS 
BEGIN 

	DECLARE @FATURAMENTO FLOAT--
	SELECT @FATURAMENTO = SUM(INF.QUANTIDADE*INF.PREÇO) FROM ITEM_NF INF
	JOIN NF ON INF.NUMERO = NF.NUMERO
	JOIN CLIENTES C ON NF.CPF = C.CPF
	WHERE C.BAIRRO = @bairro

RETURN @FATURAMENTO
END;

SELECT dbo.FaturamentoTotal('Tijuca') AS Faturamento;

