CREATE FUNCTION <NOMEFUNCAO>
RETURNS <TIPORETORNO>
AS
BEGIN
--CORPO FUNÇAO
RETURN <VARIAVELRETORNO>
END

CREATE FUNCTION FaturamentoNota (@NUMERO AS INT)
RETURNS FLOAT
AS 

BEGIN
	 
	DECLARE @FATURAMENTO FLOAT;
	SELECT @FATURAMENTO = SUM(QUANTIDADE * PREÇO)--atribui
	FROM dbo.ITEM_NF
	where NUMERO = @NUMERO
	return @FATURAMENTO
END;

--tem que usar dbo.
SELECT dbo.FaturamentoNota(NUMERO) AS FATURAAA FROM dbo.NF

