--SOMA QUANTIDADE DE TEMPO
DATEADD = DATEADD(DAY, 30, '2022-01-01')
--YEAR, QUARTER,MONTH, DAYOFYEAR, DAY, WEEK, HOUR,MINUTE,SECOND

--RETORNA A DIFERENÇA
DATEDIFF ( datepart, startdate, enddate)
DATEDIFF (DAY, '2022-01-01','2022-04-12')

--DATEPART RETORNA UMA PARTE DA DATA
DATEPART(datepart, date)
DATEPART( DAY, '2022-01-01')

--RETORNA A HORA E DATA DO PC ONDE O BDD TA RODANDO
GETDATE()

DAY(data)
MONTH(data)
YEAR(data)

--se for data retorna 1 e se nao for 0
ISDATE(expression) 

--DATETIMEFROMPARTS
DATETIMEFROMPARTS (year, month, day, hour,minute,seconds,milliseconds)
DATETIMEFROMPARTS (2022, 12, 14, 15,34,22,30)

SELECT DATEADD(DAY,10, GETDATE()) AS DezDias, DATEDIFF(day,'2024-01-01 00:00:00.000' ,GETDATE()) DiasDesdeInicioAno,

SELECT GETDATE(), DATEPART(MONTH, GETDATE())

SELECT ISDATE(DATETIMEFROMPARTS(2019,02,29,00,00,00)

SELECT NOME, (DATENAME(DAY,CLIENTES.[DATA DE NASCIMENTO]) + ' ' + DATENAME(MONTH,CLIENTES.[DATA DE NASCIMENTO])+ ' ' + DATENAME(YEAR,CLIENTES.[DATA DE NASCIMENTO])) FROM CLIENTES


SELECT * FROM SB1010 WHERE B1_DESC
