--Ate agora
--SELECT DISTINCT TOP X <LISTA DE CAMPOS> 
--FROM <TABELA>
--WHERE <FILTRO>
--GROUP BY <LISTA DE CAMPOS>
--ORDER BY <LISTA DE CAMPOS>
--HAVING <FILTRO ENVOLVENDO AGREGACAO>

--limitar agregação
SELECT * FROM CLIENTES
SELECT ESTADO, sum([LIMITE DE CREDITO]) AS CREDITO from CLIENTES
GROUP BY ESTADO

--VAI APARECER SÓ RJ
SELECT ESTADO, AVG([LIMITE DE CREDITO]) AS CREDITO from CLIENTES
GROUP BY ESTADO
HAVING SUM([LIMITE DE CREDITO]) >900000

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS PRECO_MAX, MIN([PREÇO DE LISTA]) AS PRECO_MIN
FROM PRODUTOS GROUP BY EMBALAGEM

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS PRECO_MAX, MIN([PREÇO DE LISTA]) AS PRECO_MIN
FROM PRODUTOS
WHERE [PREÇO DE LISTA] >= 10
GROUP BY EMBALAGEM
HAVING MAX([PREÇO DE LISTA]) >20--FILTRA A SAIDA DO WHERE


--Para obter o resultado esperado, nós podemos realizar 
--uma consulta na tabela de itens notas fiscais, utilizando
--a função de agregação SUM para somar a quantidade e ordenar a 
--saída utilizando o GROUP BY
SELECT [CODIGO DO PRODUTO], SUM(QUANTIDADE) SOMA_QUANTIDADE
FROM ITEM_NF
GROUP BY [CODIGO DO PRODUTO]
HAVING SUM(QUANTIDADE) > 394000
ORDER BY SUM(QUANTIDADE) DESC


