SELECT 
DISTINCT
CLI.CPF [CPF CLIENTE]
,CLI.NOME
,NF.CPF [CPF NF]
FROM CLIENTES CLI
INNER JOIN NF 
ON CLI.CPF = NF.CPF

SELECT COUNT(*) FROM CLIENTES

INSERT INTO CLIENTES
(CPF, NOME, [ENDERECO 1], [ENDERECO 2],BAIRRO,CIDADE,ESTADO,CEP,[DATA DE NASCIMENTO],IDADE, [LIMITE DE CREDITO],[VOLUME DE COMPRA],[PRIMEIRA COMPRA])
VALUES
('29466829132','Juliana Silva', 'R. Tamandai','','Bangu', 'Rio de Janeiro', 'RJ','23000012','1989-02-04',33, 180000,24500,0)
--Quais clientes que não efetuaram compras
SELECT DISTINCT
CLI.CPF [CPF CLIENTE]
,CLI.NOME
,NF.CPF [CPF NF]
FROM CLIENTES CLI LEFT JOIN NF 
ON CLI.CPF = NF.CPF
WHERE NF.CPF IS NULL

SELECT DISTINCT
VEN.NOME [NOME DO VENDEDOR]
,VEN.BAIRRO [BAIRRO DO VENDEDOR]
,CLI.NOME [NOME DO CLIENTE]
,CLI.BAIRRO [BAIRRO DO CLIENTE]
FROM VENDEDORES VEN
LEFT JOIN CLIENTES CLI ON VEN.BAIRRO = CLI.BAIRRO
WHERE CLI.BAIRRO IS NULL


SELECT DISTINCT
VEN.NOME [NOME DO VENDEDOR]
,VEN.BAIRRO [BAIRRO DO VENDEDOR]
,CLI.NOME [NOME DO CLIENTE]
,CLI.BAIRRO [BAIRRO DO CLIENTE]
FROM VENDEDORES VEN
FULL JOIN CLIENTES CLI ON VEN.BAIRRO = CLI.BAIRRO
WHERE CLI.BAIRRO IS NULL
