SELECT * FROM [NOTAS FISCAIS]
SELECT * FROM [TABELA DE VENDEDORES]

SELECT * FROM [TABELA DE VENDEDORES] 
INNER JOIN [NOTAS FISCAIS] ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA

--
SELECT VENDEDORES.MATRICULA, VENDEDORES.NOME FROM VENDEDORES 
JOIN NF ON VENDEDORES.MATRICULA=NF.MATRICULA
GROUP BY 

SELECT * FROM NF
SELECT * FROM ITEM_NF

SELECT 
YEAR(DATA), 
FORMAT(SUM (QUANTIDADE * [PREÇO]), 'C', 'en-us') AS FATURAMENTO--N,G,C
FROM  NF INNER JOIN ITEM_NF INF
ON NF.NUMERO = INF.NUMERO
GROUP BY YEAR(DATA)


--LEFT
SELECT CLIENTES.NOME, COUNT (*) 
FROM CLIENTES 
LEFT JOIN NF ON NF.CPF = CLIENTES.CPF
GROUP BY CLIENTES.NOME