SELECT * FROM [dbo].[TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA]

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA] DESC

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [NOME DO PRODUTO]

SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM], [NOME DO PRODUTO]

SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM] DESC, [NOME DO PRODUTO] ASC


--EXERCICIO
--Qual foi a maior venda do produto "Linha Refrescante - 1 Litro - Morango/Limão", em quantidade?
SELECT TOP 1 PRDT.[NOME DO PRODUTO], ITNS.QUANTIDADE  
FROM [ITENS NOTAS FISCAIS] ITNS
JOIN [TABELA DE PRODUTOS] PRDT ON ITNS.[CODIGO DO PRODUTO]=PRDT.[CODIGO DO PRODUTO]
WHERE [NOME DO PRODUTO]='Linha Refrescante - 1 Litro - Morango/Limão' 
ORDER BY QUANTIDADE DESC


