--STORAGE PRA ATUALIZAR A IDADE 
CREATE PROCEDURE CalculaIdade
AS
BEGIN
	UPDATE CLIENTES SET IDADE = DATEDIFF(YEAR, [DATA DE NASCIMENTO],GETDATE())
END

--EXECUTANDO PROCEDURE
--acertando idade da base
EXEC dbo.CalculaIdade