IF OBJECT_ID( 'TABELA_TESTE','U') IS NOT NULL DROP TABLE TABELA_TESTE;
IF OBJECT_ID('TABELA_TESTE','U') IS NULL CREATE TABLE TABELA_TESTE (ID VARCHAR(10));
---
select GETDATE()
SELECT DATENAME(WEEKDAY, GETDATE())
--
DECLARE @DIA_SEMANA VARCHAR(20);
DECLARE @NUMERO_DIAS INT;

SET @NUMERO_DIAS=10
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()));
PRINT @DIA_SEMANA
IF @DIA_SEMANA = 'Domingo' OR @DIA_SEMANA= 'Sábado'
	PRINT 'DIA INUTIL'
ELSE
	PRINT 'DIA UTIL'
	--
DECLARE @CPF VARCHAR(15);
   DECLARE @DATA_NASCIMENTO DATE;
   DECLARE @IDADE INT;
   DECLARE @_IDADE INT 
   SET @CPF = '1471156710';
   SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE=IDADE FROM CLIENTES WHERE CPF = @CPF;
   SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());
	   IF @IDADE <> @_IDADE
		UPDATE CLIENTES SET IDADE = @IDADE WHERE CPF = @CPF;
--

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) SOMA_CREDITO FROM CLIENTES GROUP BY BAIRRO

DECLARE @LIM_MAX FLOAT;
DECLARE @LIM_ATU FLOAT;
DECLARE @BAIRRO  VARCHAR(20);

SET @LIM_MAX = 50000;
SET @BAIRRO = 'Água Santa';
SELECT @LIM_ATU = SUM([LIMITE DE CREDITO]) FROM CLIENTES WHERE BAIRRO = @BAIRRO;
IF @LIM_ATU > @LIM_MAX
	PRINT 'Limite de crédito excedido';
ELSE 
	PRINT 'Limite de crédito válido'
--de forma mais direta
DECLARE @LIM_MAX FLOAT;
DECLARE @BAIRRO  VARCHAR(20);

SET @LIM_MAX = 50000;
SET @BAIRRO = 'Água Santa';
IF (select SUM([LIMITE DE CREDITO]) FROM CLIENTES WHERE BAIRRO = @BAIRRO) > @LIM_MAX
	PRINT 'Limite de crédito excedido';
ELSE 
	PRINT 'Limite de crédito válido'


----desafio
--Diante dessa possibilidade, como podemos reescrever este SCRIPT usando um SELECT no teste do IF?
DECLARE @CPF VARCHAR(15);
DECLARE @IDADE_TABELA INT;
DECLARE @DATA_NASCIMENTO DATE;
--DECLARE @IDADE INT;

SET @CPF = '1471156710';
SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE_TABELA = IDADE FROM CLIENTES WHERE CPF = @CPF;
--SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());
IF @IDADE_TABELA <> DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE()) UPDATE CLIENTES SET IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE()) WHERE CPF = @CPF;