USE SUCOS_VENDAS
DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT;
DECLARE @DATA DATE, @FERIAS BIT, @BAIRRO VARCHAR(50);

SET @MATRICULA = '000240'
SET @NOME = 'Cláudia Rodrigues';
SET @PERCENTUAL = 0.10;
SET @DATA = '2012-03-12';
SET @FERIAS = 1;
SET @BAIRRO = 'Jardins';

insert into VENDEDORES
(MATRICULA,NOME,[PERCENTUAL COMISSÃO],[DATA ADMISSÃO],[DE FERIAS],BAIRRO)
values
(@MATRICULA,@NOME,@PERCENTUAL,@DATA,@FERIAS,@BAIRRO)

PRINT 'UM VENDEDOR INCLUIDO...'

SET @MATRICULA = '000244'
SET @NOME = 'Roberto Araujo';

insert into VENDEDORES
(MATRICULA,NOME,[PERCENTUAL COMISSÃO],[DATA ADMISSÃO],[DE FERIAS],BAIRRO)
values
(@MATRICULA,@NOME,@PERCENTUAL,@DATA,@FERIAS,@BAIRRO)

PRINT 'UM VENDEDOR INCLUIDO...'

PRINT @MATRICULA;
PRINT @NOME;

SELECT * FROM VENDEDORES
---
   DECLARE @CPF VARCHAR(15);
   DECLARE @DATA_NASCIMENTO DATE;
   DECLARE @IDADE INT;

   SET @CPF = '1471156710';
   SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO] FROM [CLIENTES] WHERE CPF = @CPF;
   SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());
   PRINT @IDADE;

   UPDATE CLIENTES
   SET IDADE = @IDADE
   WHERE 
   CPF= @CPF
   SELECT * FROM CLIENTES

   ---
   DECLARE @CPF VARCHAR(50);
   DECLARE @NOME VARCHAR(100);
   DECLARE @DATA_NASCIMENTO DATE;
   DECLARE @IDADE INT;
   DECLARE @SAIDA VARCHAR(500)
   SET @CPF = '1471156710';
   SET @SAIDA = 'O primeiro nome do cliente '+ @NOME + ' cujo CPF é ' +@CPF + ' corresponde a ' + SUBSTRING(@NOME, 1, CHARINDEX(' ',@NOME)-1);
   SELECT @NOME	 = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO],
   @IDADE = IDADE FROM [CLIENTES] WHERE CPF = @CPF
   PRINT @SAIDA;
   --PRINT 'O primeiro nome do cliente '+ @NOME + ' cujo CPF é ' +@CPF + ' corresponde a ' + SUBSTRING(@NOME, 1, CHARINDEX(' ',@NOME)-1);
   PRINT @DATA_NASCIMENTO
   PRINT @IDADE

 --  SELECT * FROM CLIENTES
 --  1471156710
	--19290992743
	--2600586709
	--S
	DECLARE @NUMNOTAS INT
	SELECT @NUMNOTAS = COUNT(*) FROM NF
	WHERE DATA='2017-01-01'

	PRINT @NUMNOTAS

-----

--USANDO FUNÇÃO COM PRINT
SELECT NOME, CHARINDEX(' ', NOME), SUBSTRING(NOME, 1, CHARINDEX(' ',NOME)-1) FROM CLIENTES


--Como faríamos para repetir o mesmo SCRIPT sem usar a variável @IDADE?
DECLARE @CPF VARCHAR(15);
DECLARE @DATA_NASCIMENTO DATE;
DECLARE @IDADE INT;

SET @CPF = '1471156710';

SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO] FROM CLIENTES WHERE CPF = @CPF;
--@IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());
PRINT DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());
--PRINT @IDADE;

