SELECT INF.[CODIGO DO PRODUTO], TP.[NOME DO PRODUTO], SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITEM_NF  INF
INNER JOIN PRODUTOS TP 
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
GROUP BY INF.[CODIGO DO PRODUTO], TP.[NOME DO PRODUTO] HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;


SELECT DISTINCT SABOR FROM PRODUTOS WHERE
[CODIGO DO PRODUTO] IN (
SELECT INF.[CODIGO DO PRODUTO] FROM ITEM_NF  INF
INNER JOIN PRODUTOS TP 
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
GROUP BY INF.[CODIGO DO PRODUTO], TP.[NOME DO PRODUTO] HAVING SUM(INF.QUANTIDADE) > 394000 );