--UNIIIIIIIIIIOM
--Ele traz já aplicando o distinct
--se coloca UNION ALL ele vem sem o distinct

SELECT DISTINCT BAIRRO FROM CLIENTES
SELECT DISTINCT BAIRRO FROM VENDEDORES

SELECT DISTINCT BAIRRO FROM CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM VENDEDORES
--COLOCAR ORIGEM
SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM VENDEDORES