CREATE VIEW VW_MEDIA_EMBALAGENS AS
SELECT EMBALAGEM,
	AVG([PREÇO DE LISTA]) AS PRECO_MEDIO
	FROM PRODUTOS
	GROUP BY EMBALAGEM

	--
CREATE VIEW VW_ProdutoXquantidade AS
SELECT INF.[CODIGO DO PRODUTO], TP.[NOME DO PRODUTO], SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITEM_NF  INF
INNER JOIN PRODUTOS TP 
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
GROUP BY INF.[CODIGO DO PRODUTO], TP.[NOME DO PRODUTO] HAVING SUM(INF.QUANTIDADE) > 394000 

CREATE VIEW
SELECT INF.[CODIGO DO PRODUTO], TP.[NOME DO PRODUTO], SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITEM_NF  INF
INNER JOIN PRODUTOS TP 
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]